/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as PoliticaDeEntregaRouteImport } from './routes/politica-de-entrega'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PromocoesRouteImport } from './routes/promocoes'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as TrocasEDevolucoesRouteImport } from './routes/trocas-e-devolucoes'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as ApiMercadoPagoWebhookRouteImport } from './routes/api/mercado-pago/webhook'
import { Route as ApiOrdersPaymentRemindersRouteImport } from './routes/api/orders/payment-reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeEntregaRoute = PoliticaDeEntregaRouteImport.update({
  id: '/politica-de-entrega',
  path: '/politica-de-entrega',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocoesRoute = PromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocasEDevolucoesRoute = TrocasEDevolucoesRouteImport.update({
  id: '/trocas-e-devolucoes',
  path: '/trocas-e-devolucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMercadoPagoWebhookRoute = ApiMercadoPagoWebhookRouteImport.update({
  id: '/api/mercado-pago/webhook',
  path: '/api/mercado-pago/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersPaymentRemindersRoute =
  ApiOrdersPaymentRemindersRouteImport.update({
    id: '/api/orders/payment-reminders',
    path: '/api/orders/payment-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/entrar': typeof EntrarRoute
  '/pagamento': typeof PagamentoRoute
  '/politica-de-entrega': typeof PoliticaDeEntregaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/promocoes': typeof PromocoesRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/trocas-e-devolucoes': typeof TrocasEDevolucoesRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/mercado-pago/webhook': typeof ApiMercadoPagoWebhookRoute
  '/api/orders/payment-reminders': typeof ApiOrdersPaymentRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/entrar': typeof EntrarRoute
  '/pagamento': typeof PagamentoRoute
  '/politica-de-entrega': typeof PoliticaDeEntregaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/promocoes': typeof PromocoesRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/trocas-e-devolucoes': typeof TrocasEDevolucoesRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/mercado-pago/webhook': typeof ApiMercadoPagoWebhookRoute
  '/api/orders/payment-reminders': typeof ApiOrdersPaymentRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/entrar': typeof EntrarRoute
  '/pagamento': typeof PagamentoRoute
  '/politica-de-entrega': typeof PoliticaDeEntregaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/promocoes': typeof PromocoesRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/trocas-e-devolucoes': typeof TrocasEDevolucoesRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/mercado-pago/webhook': typeof ApiMercadoPagoWebhookRoute
  '/api/orders/payment-reminders': typeof ApiOrdersPaymentRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/conta'
    | '/contato'
    | '/entrar'
    | '/pagamento'
    | '/politica-de-entrega'
    | '/politica-de-privacidade'
    | '/produtos'
    | '/promocoes'
    | '/sobre'
    | '/termos-de-uso'
    | '/trocas-e-devolucoes'
    | '/produto/$slug'
    | '/api/mercado-pago/webhook'
    | '/api/orders/payment-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/conta'
    | '/contato'
    | '/entrar'
    | '/pagamento'
    | '/politica-de-entrega'
    | '/politica-de-privacidade'
    | '/produtos'
    | '/promocoes'
    | '/sobre'
    | '/termos-de-uso'
    | '/trocas-e-devolucoes'
    | '/produto/$slug'
    | '/api/mercado-pago/webhook'
    | '/api/orders/payment-reminders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/conta'
    | '/contato'
    | '/entrar'
    | '/pagamento'
    | '/politica-de-entrega'
    | '/politica-de-privacidade'
    | '/produtos'
    | '/promocoes'
    | '/sobre'
    | '/termos-de-uso'
    | '/trocas-e-devolucoes'
    | '/produto/$slug'
    | '/api/mercado-pago/webhook'
    | '/api/orders/payment-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  ContaRoute: typeof ContaRoute
  ContatoRoute: typeof ContatoRoute
  EntrarRoute: typeof EntrarRoute
  PagamentoRoute: typeof PagamentoRoute
  PoliticaDeEntregaRoute: typeof PoliticaDeEntregaRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  ProdutosRoute: typeof ProdutosRoute
  PromocoesRoute: typeof PromocoesRoute
  SobreRoute: typeof SobreRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  TrocasEDevolucoesRoute: typeof TrocasEDevolucoesRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiMercadoPagoWebhookRoute: typeof ApiMercadoPagoWebhookRoute
  ApiOrdersPaymentRemindersRoute: typeof ApiOrdersPaymentRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-entrega': {
      id: '/politica-de-entrega'
      path: '/politica-de-entrega'
      fullPath: '/politica-de-entrega'
      preLoaderRoute: typeof PoliticaDeEntregaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promocoes': {
      id: '/promocoes'
      path: '/promocoes'
      fullPath: '/promocoes'
      preLoaderRoute: typeof PromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocas-e-devolucoes': {
      id: '/trocas-e-devolucoes'
      path: '/trocas-e-devolucoes'
      fullPath: '/trocas-e-devolucoes'
      preLoaderRoute: typeof TrocasEDevolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mercado-pago/webhook': {
      id: '/api/mercado-pago/webhook'
      path: '/api/mercado-pago/webhook'
      fullPath: '/api/mercado-pago/webhook'
      preLoaderRoute: typeof ApiMercadoPagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/payment-reminders': {
      id: '/api/orders/payment-reminders'
      path: '/api/orders/payment-reminders'
      fullPath: '/api/orders/payment-reminders'
      preLoaderRoute: typeof ApiOrdersPaymentRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  ContaRoute: ContaRoute,
  ContatoRoute: ContatoRoute,
  EntrarRoute: EntrarRoute,
  PagamentoRoute: PagamentoRoute,
  PoliticaDeEntregaRoute: PoliticaDeEntregaRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  ProdutosRoute: ProdutosRoute,
  PromocoesRoute: PromocoesRoute,
  SobreRoute: SobreRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  TrocasEDevolucoesRoute: TrocasEDevolucoesRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiMercadoPagoWebhookRoute: ApiMercadoPagoWebhookRoute,
  ApiOrdersPaymentRemindersRoute: ApiOrdersPaymentRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
